// Copyright (c) 2024-2024 by Raphaël Lemaitre and Contributors
// This software is licensed under the Eclipse Public License v2.0 (EPL-2.0).
// For more information see LICENSE or https://opensource.org/license/epl-2-0

package io.funktional.yggdrasil.marc

import io.funktional.yggdrasil.Maybe
import io.funktional.yggdrasil.syntax.all.*

/**
 * MARC country codes.
 * 
 * @see https://www.loc.gov/marc/countries/countries_code.html
 * @param code The MARC code.
 * @param name The name of the country.
 * @param discontinued True if the code is discontinued, false otherwise.
 */
enum Country(val code: String, val name: String, val discontinued: Boolean):
    case Afghanistan                                              extends Country("af", "Afghanistan", discontinued = false)
    case Alabama                                                  extends Country("alu", "Alabama", discontinued = false)
    case Alaska                                                   extends Country("aku", "Alaska", discontinued = false)
    case Albania                                                  extends Country("aa", "Albania", discontinued = false)
    case Alberta                                                  extends Country("abc", "Alberta", discontinued = false)
    case Algeria                                                  extends Country("ae", "Algeria", discontinued = false)
    case AmericanSamoa                                            extends Country("as", "American Samoa", discontinued = false)
    case Andorra                                                  extends Country("an", "Andorra", discontinued = false)
    case Angola                                                   extends Country("ao", "Angola", discontinued = false)
    case Anguilla                                                 extends Country("am", "Anguilla", discontinued = false)
    @deprecated("This code is no longer in use") case AnguillaOld extends Country("ai", "Anguilla", discontinued = true)
    case Antarctica                                               extends Country("ay", "Antarctica", discontinued = false)
    case AntiguaAndBarbuda                                        extends Country("aq", "Antigua and Barbuda", discontinued = false)
    case Argentina                                                extends Country("ag", "Argentina", discontinued = false)
    case Arizona                                                  extends Country("azu", "Arizona", discontinued = false)
    case Arkansas                                                 extends Country("aru", "Arkansas", discontinued = false)
    case Armenia                                                  extends Country("ai", "Armenia (Republic)", discontinued = false)
    @deprecated("This code is no longer in use") case ArmenianSSR
        extends Country("air", "Armenian S.S.R.", discontinued = true)
    case Aruba                                                    extends Country("aw", "Aruba", discontinued = false)
    @deprecated("This code is no longer in use") case AshmoreAndCartierIslands
        extends Country("ac", "Ashmore and Cartier Islands", discontinued = true)
    case Australia                                                extends Country("at", "Australia", discontinued = false)
    case AustralianCapitalTerritory                               extends Country("aca", "Australian Capital Territory", discontinued = false)
    case Austria                                                  extends Country("au", "Austria", discontinued = false)
    case Azerbaijan                                               extends Country("aj", "Azerbaijan", discontinued = false)
    @deprecated("This code is no longer in use") case AzerbaijanSSR
        extends Country("ajr", "Azerbaijan S.S.R.", discontinued = true)
    case Bahamas                                                  extends Country("bf", "Bahamas", discontinued = false)
    case Bahrain                                                  extends Country("ba", "Bahrain", discontinued = false)
    case Bangladesh                                               extends Country("bg", "Bangladesh", discontinued = false)
    case Barbados                                                 extends Country("bb", "Barbados", discontinued = false)
    case Belarus                                                  extends Country("bw", "Belarus", discontinued = false)
    case Belgium                                                  extends Country("be", "Belgium", discontinued = false)
    case Belize                                                   extends Country("bh", "Belize", discontinued = false)
    case Benin                                                    extends Country("dm", "Benin", discontinued = false)
    case BermudaIslands                                           extends Country("bm", "Bermuda Islands", discontinued = false)
    case Bhutan                                                   extends Country("bt", "Bhutan", discontinued = false)
    case Bolivia                                                  extends Country("bo", "Bolivia", discontinued = false)
    case BosniaAndHerzegovina                                     extends Country("bn", "Bosnia and Herzegovina", discontinued = false)
    case Botswana                                                 extends Country("bs", "Botswana", discontinued = false)
    case BouvetIsland                                             extends Country("bv", "Bouvet Island", discontinued = false)
    case Brazil                                                   extends Country("bl", "Brazil", discontinued = false)
    case BritishColumbia                                          extends Country("bcc", "British Columbia", discontinued = false)
    case BritishIndianOceanTerritory                              extends Country("bi", "British Indian Ocean Territory", discontinued = false)
    case BritishVirginIslands                                     extends Country("vb", "British Virgin Islands", discontinued = false)
    case Brunei                                                   extends Country("bx", "Brunei", discontinued = false)
    case Bulgaria                                                 extends Country("bu", "Bulgaria", discontinued = false)
    case BurkinaFaso                                              extends Country("uv", "Burkina Faso", discontinued = false)
    case Burma                                                    extends Country("br", "Burma", discontinued = false)
    case Burundi                                                  extends Country("bd", "Burundi", discontinued = false)
    @deprecated("This code is no longer in use") case ByelorussianSSR
        extends Country("bwr", "Byelorussian S.S.R.", discontinued = true)
    case CaboVerde                                                extends Country("cv", "Cabo Verde", discontinued = false)
    case California                                               extends Country("cau", "California", discontinued = false)
    case Cambodia                                                 extends Country("cb", "Cambodia", discontinued = false)
    case Cameroon                                                 extends Country("cm", "Cameroon", discontinued = false)
    case Canada                                                   extends Country("xxc", "Canada", discontinued = false)
    @deprecated("This code is no longer in use") case CanadaOld   extends Country("cn", "Canada", discontinued = true)
    @deprecated("This code is no longer in use") case CanalZone   extends Country("cz", "Canal Zone", discontinued = true)
    @deprecated("This code is no longer in use") case CantonAndEnderburyIslands
        extends Country("cp", "Canton and Enderbury Islands", discontinued = true)
    case CaribbeanNetherlands                                     extends Country("ca", "Caribbean Netherlands", discontinued = false)
    case CaymanIslands                                            extends Country("cj", "Cayman Islands", discontinued = false)
    case CentralAfricanRepublic                                   extends Country("cx", "Central African Republic", discontinued = false)
    @deprecated("This code is no longer in use") case CentralAndSouthernLineIslands
        extends Country("ln", "Central and Southern Line Islands", discontinued = true)
    case Chad                                                     extends Country("cd", "Chad", discontinued = false)
    case Chile                                                    extends Country("cl", "Chile", discontinued = false)
    case ChinaOld                                                 extends Country("cc", "China", discontinued = false)
    case ChinaRepublic                                            extends Country("ch", "China (Republic : 1949- )", discontinued = false)
    case ChristmasIsland                                          extends Country("xa", "Christmas Island (Indian Ocean)", discontinued = false)
    case CocosIslands                                             extends Country("xb", "Cocos (Keeling) Islands", discontinued = false)
    case Colombia                                                 extends Country("ck", "Colombia", discontinued = false)
    case Colorado                                                 extends Country("cou", "Colorado", discontinued = false)
    case Comoros                                                  extends Country("cq", "Comoros", discontinued = false)
    case CongoBrazzaville                                         extends Country("cf", "Congo (Brazzaville)", discontinued = false)
    case CongoDemocraticRepublic                                  extends Country("cg", "Congo (Democratic Republic)", discontinued = false)
    case Connecticut                                              extends Country("ctu", "Connecticut", discontinued = false)
    case CookIslands                                              extends Country("cw", "Cook Islands", discontinued = false)
    case CoralSeaIslandsTerritory                                 extends Country("xga", "Coral Sea Islands Territory", discontinued = false)
    case CostaRica                                                extends Country("cr", "Costa Rica", discontinued = false)
    case CoteDIvoire                                              extends Country("iv", "Côte d'Ivoire", discontinued = false)
    case Croatia                                                  extends Country("ci", "Croatia", discontinued = false)
    case Cuba                                                     extends Country("cu", "Cuba", discontinued = false)
    case Curacao                                                  extends Country("co", "Curaçao", discontinued = false)
    case Cyprus                                                   extends Country("cy", "Cyprus", discontinued = false)
    case CzechRepublic                                            extends Country("xr", "Czech Republic", discontinued = false)
    @deprecated("This code is no longer in use") case Czechoslovakia
        extends Country("cs", "Czechoslovakia", discontinued = true)
    case Delaware                                                 extends Country("deu", "Delaware", discontinued = false)
    case Denmark                                                  extends Country("dk", "Denmark", discontinued = false)
    case DistrictOfColumbia                                       extends Country("dcu", "District of Columbia", discontinued = false)
    case Djibouti                                                 extends Country("ft", "Djibouti", discontinued = false)
    case Dominica                                                 extends Country("dq", "Dominica", discontinued = false)
    case DominicanRepublic                                        extends Country("dr", "Dominican Republic", discontinued = false)
    @deprecated("This code is no longer in use") case EastGermany
        extends Country("ge", "Germany (East)", discontinued = true)
    case Ecuador                                                  extends Country("ec", "Ecuador", discontinued = false)
    case Egypt                                                    extends Country("ua", "Egypt", discontinued = false)
    case ElSalvador                                               extends Country("es", "El Salvador", discontinued = false)
    case England                                                  extends Country("enk", "England", discontinued = false)
    case EquatorialGuinea                                         extends Country("eg", "Equatorial Guinea", discontinued = false)
    case Eritrea                                                  extends Country("ea", "Eritrea", discontinued = false)
    case EstoniaOld                                               extends Country("er", "Estonia", discontinued = false)
    @deprecated("This code is no longer in use") case EstoniaOld2 extends Country("err", "Estonia", discontinued = true)
    case Eswatini                                                 extends Country("sq", "Eswatini", discontinued = false)
    case Ethiopia                                                 extends Country("et", "Ethiopia", discontinued = false)
    case FalklandIslands                                          extends Country("fk", "Falkland Islands", discontinued = false)
    case FaroeIslands                                             extends Country("fa", "Faroe Islands", discontinued = false)
    case Fiji                                                     extends Country("fj", "Fiji", discontinued = false)
    case Finland                                                  extends Country("fi", "Finland", discontinued = false)
    case Florida                                                  extends Country("flu", "Florida", discontinued = false)
    case France                                                   extends Country("fr", "France", discontinued = false)
    case FrenchGuiana                                             extends Country("fg", "French Guiana", discontinued = false)
    case FrenchPolynesia                                          extends Country("fp", "French Polynesia", discontinued = false)
    case Gabon                                                    extends Country("go", "Gabon", discontinued = false)
    case Gambia                                                   extends Country("gm", "Gambia", discontinued = false)
    case GazaStrip                                                extends Country("gz", "Gaza Strip", discontinued = false)
    case Georgia                                                  extends Country("gau", "Georgia", discontinued = false)
    case GeorgiaRepublic                                          extends Country("gs", "Georgia (Republic)", discontinued = false)
    @deprecated("This code is no longer in use") case GeorgianSSR
        extends Country("gsr", "Georgian S.S.R.", discontinued = true)
    case Germany                                                  extends Country("gw", "Germany", discontinued = false)
    case Ghana                                                    extends Country("gh", "Ghana", discontinued = false)
    case Gibraltar                                                extends Country("gi", "Gibraltar", discontinued = false)
    @deprecated("This code is no longer in use") case GilbertAndElliceIslands
        extends Country("gn", "Gilbert and Ellice Islands", discontinued = true)
    case Greece                                                   extends Country("gr", "Greece", discontinued = false)
    case Greenland                                                extends Country("gl", "Greenland", discontinued = false)
    case Grenada                                                  extends Country("gd", "Grenada", discontinued = false)
    case Guadeloupe                                               extends Country("gp", "Guadeloupe", discontinued = false)
    case Guam                                                     extends Country("gu", "Guam", discontinued = false)
    case Guatemala                                                extends Country("gt", "Guatemala", discontinued = false)
    case Guernsey                                                 extends Country("gg", "Guernsey", discontinued = false)
    case Guinea                                                   extends Country("gv", "Guinea", discontinued = false)
    case GuineaBissau                                             extends Country("pg", "Guinea-Bissau", discontinued = false)
    case Guyana                                                   extends Country("gy", "Guyana", discontinued = false)
    case Haiti                                                    extends Country("ht", "Haiti", discontinued = false)
    case Hawaii                                                   extends Country("hiu", "Hawaii", discontinued = false)
    case HeardAndMcDonaldIslands                                  extends Country("hm", "Heard and McDonald Islands", discontinued = false)
    case Honduras                                                 extends Country("ho", "Honduras", discontinued = false)
    @deprecated("This code is no longer in use") case HongKong    extends Country("hk", "Hong Kong", discontinued = true)
    case Hungary                                                  extends Country("hu", "Hungary", discontinued = false)
    case Iceland                                                  extends Country("ic", "Iceland", discontinued = false)
    case Idaho                                                    extends Country("idu", "Idaho", discontinued = false)
    case Illinois                                                 extends Country("ilu", "Illinois", discontinued = false)
    case India                                                    extends Country("ii", "India", discontinued = false)
    case Indiana                                                  extends Country("inu", "Indiana", discontinued = false)
    case Indonesia                                                extends Country("io", "Indonesia", discontinued = false)
    case Iowa                                                     extends Country("iau", "Iowa", discontinued = false)
    case Iran                                                     extends Country("ir", "Iran", discontinued = false)
    case Iraq                                                     extends Country("iq", "Iraq", discontinued = false)
    case IraqSaudiArabiaNeutralZone                               extends Country("iy", "Iraq-Saudi Arabia Neutral Zone", discontinued = false)
    case Ireland                                                  extends Country("ie", "Ireland", discontinued = false)
    case IsleOfMan                                                extends Country("im", "Isle of Man", discontinued = false)
    case Israel                                                   extends Country("is", "Israel", discontinued = false)
    @deprecated("This code is no longer in use") case IsraelJordanDemilitarizedZones
        extends Country("iw", "Israel-Jordan Demilitarized Zones", discontinued = true)
    @deprecated("This code is no longer in use") case IsraelSyriaDemilitarizedZones
        extends Country("iu", "Israel-Syria Demilitarized Zones", discontinued = true)
    case Italy                                                    extends Country("it", "Italy", discontinued = false)
    case Jamaica                                                  extends Country("jm", "Jamaica", discontinued = false)
    @deprecated("This code is no longer in use") case JanMayen    extends Country("jn", "Jan Mayen", discontinued = true)
    case Japan                                                    extends Country("ja", "Japan", discontinued = false)
    case Jersey                                                   extends Country("je", "Jersey", discontinued = false)
    case JohnstonAtoll                                            extends Country("ji", "Johnston Atoll", discontinued = false)
    case Jordan                                                   extends Country("jo", "Jordan", discontinued = false)
    case Kansas                                                   extends Country("ksu", "Kansas", discontinued = false)
    @deprecated("This code is no longer in use") case KazakhSSR
        extends Country("kzr", "Kazakh S.S.R.", discontinued = true)
    case Kazakhstan                                               extends Country("kz", "Kazakhstan", discontinued = false)
    case Kentucky                                                 extends Country("kyu", "Kentucky", discontinued = false)
    case Kenya                                                    extends Country("ke", "Kenya", discontinued = false)
    @deprecated("This code is no longer in use") case KirghizSSR
        extends Country("kgr", "Kirghiz S.S.R.", discontinued = true)
    case Kiribati                                                 extends Country("gb", "Kiribati", discontinued = false)
    case Kosovo                                                   extends Country("kv", "Kosovo", discontinued = false)
    case Kuwait                                                   extends Country("ku", "Kuwait", discontinued = false)
    case Kyrgyzstan                                               extends Country("kg", "Kyrgyzstan", discontinued = false)
    case Laos                                                     extends Country("ls", "Laos", discontinued = false)
    case Latvia                                                   extends Country("lv", "Latvia", discontinued = false)
    @deprecated("This code is no longer in use") case LatviaOld   extends Country("lvr", "Latvia", discontinued = true)
    case Lebanon                                                  extends Country("le", "Lebanon", discontinued = false)
    case Lesotho                                                  extends Country("lo", "Lesotho", discontinued = false)
    case Liberia                                                  extends Country("lb", "Liberia", discontinued = false)
    case Libya                                                    extends Country("ly", "Libya", discontinued = false)
    case Liechtenstein                                            extends Country("lh", "Liechtenstein", discontinued = false)
    case Lithuania                                                extends Country("li", "Lithuania", discontinued = false)
    @deprecated("This code is no longer in use") case LithuaniaOld
        extends Country("lir", "Lithuania", discontinued = true)
    case Louisiana                                                extends Country("lau", "Louisiana", discontinued = false)
    case Luxembourg                                               extends Country("lu", "Luxembourg", discontinued = false)
    @deprecated("This code is no longer in use") case Macao       extends Country("mh", "Macao", discontinued = true)
    case Madagascar                                               extends Country("mg", "Madagascar", discontinued = false)
    case Maine                                                    extends Country("meu", "Maine", discontinued = false)
    case Malawi                                                   extends Country("mw", "Malawi", discontinued = false)
    case Malaysia                                                 extends Country("my", "Malaysia", discontinued = false)
    case Maldives                                                 extends Country("xc", "Maldives", discontinued = false)
    case Mali                                                     extends Country("ml", "Mali", discontinued = false)
    case Malta                                                    extends Country("mm", "Malta", discontinued = false)
    case Manitoba                                                 extends Country("mbc", "Manitoba", discontinued = false)
    case MarshallIslands                                          extends Country("xe", "Marshall Islands", discontinued = false)
    case Martinique                                               extends Country("mq", "Martinique", discontinued = false)
    case Maryland                                                 extends Country("mdu", "Maryland", discontinued = false)
    case Massachusetts                                            extends Country("mau", "Massachusetts", discontinued = false)
    case Mauritania                                               extends Country("mu", "Mauritania", discontinued = false)
    case Mauritius                                                extends Country("mf", "Mauritius", discontinued = false)
    case Mayotte                                                  extends Country("ot", "Mayotte", discontinued = false)
    case Mexico                                                   extends Country("mx", "Mexico", discontinued = false)
    case Michigan                                                 extends Country("miu", "Michigan", discontinued = false)
    case MicronesiaFederatedStates                                extends Country("fm", "Micronesia (Federated States)", discontinued = false)
    case MidwayIslands                                            extends Country("xf", "Midway Islands", discontinued = false)
    case Minnesota                                                extends Country("mnu", "Minnesota", discontinued = false)
    case Mississippi                                              extends Country("msu", "Mississippi", discontinued = false)
    case Missouri                                                 extends Country("mou", "Missouri", discontinued = false)
    @deprecated("This code is no longer in use") case MoldavianSSR
        extends Country("mvr", "Moldavian S.S.R.", discontinued = true)
    case Moldova                                                  extends Country("mv", "Moldova", discontinued = false)
    case Monaco                                                   extends Country("mc", "Monaco", discontinued = false)
    case Mongolia                                                 extends Country("mp", "Mongolia", discontinued = false)
    case Montana                                                  extends Country("mtu", "Montana", discontinued = false)
    case Montenegro                                               extends Country("mo", "Montenegro", discontinued = false)
    case Montserrat                                               extends Country("mj", "Montserrat", discontinued = false)
    case Morocco                                                  extends Country("mr", "Morocco", discontinued = false)
    case Mozambique                                               extends Country("mz", "Mozambique", discontinued = false)
    case Namibia                                                  extends Country("sx", "Namibia", discontinued = false)
    case Nauru                                                    extends Country("nu", "Nauru", discontinued = false)
    case Nebraska                                                 extends Country("nbu", "Nebraska", discontinued = false)
    case Nepal                                                    extends Country("np", "Nepal", discontinued = false)
    case Netherlands                                              extends Country("ne", "Netherlands", discontinued = false)
    @deprecated("This code is no longer in use") case NetherlandsAntilles
        extends Country("na", "Netherlands Antilles", discontinued = true)
    case Nevada                                                   extends Country("nvu", "Nevada", discontinued = false)
    case NewBrunswick                                             extends Country("nkc", "New Brunswick", discontinued = false)
    case NewCaledonia                                             extends Country("nl", "New Caledonia", discontinued = false)
    case NewHampshire                                             extends Country("nhu", "New Hampshire", discontinued = false)
    case NewJersey                                                extends Country("nju", "New Jersey", discontinued = false)
    case NewMexico                                                extends Country("nmu", "New Mexico", discontinued = false)
    case NewSouthWales                                            extends Country("xna", "New South Wales", discontinued = false)
    case NewYorkState                                             extends Country("nyu", "New York (State)", discontinued = false)
    case NewZealand                                               extends Country("nz", "New Zealand", discontinued = false)
    case NewfoundlandAndLabrador                                  extends Country("nfc", "Newfoundland and Labrador", discontinued = false)
    case Nicaragua                                                extends Country("nq", "Nicaragua", discontinued = false)
    case Niger                                                    extends Country("ng", "Niger", discontinued = false)
    case Nigeria                                                  extends Country("nr", "Nigeria", discontinued = false)
    case Niue                                                     extends Country("xh", "Niue", discontinued = false)
    case NoPlace                                                  extends Country("xx", "No place, unknown, or undetermined", discontinued = false)
    case NorfolkIsland                                            extends Country("nx", "Norfolk Island", discontinued = false)
    case NorthCarolina                                            extends Country("ncu", "North Carolina", discontinued = false)
    case NorthDakota                                              extends Country("ndu", "North Dakota", discontinued = false)
    case NorthKorea                                               extends Country("kn", "Korea (North)", discontinued = false)
    case NorthMacedonia                                           extends Country("xn", "North Macedonia", discontinued = false)
    @deprecated("This code is no longer in use") case NorthVietnam
        extends Country("vn", "Vietnam, North", discontinued = true)
    case NorthernIreland                                          extends Country("nik", "Northern Ireland", discontinued = false)
    case NorthernMarianaIslands                                   extends Country("nw", "Northern Mariana Islands", discontinued = false)
    @deprecated("This code is no longer in use") case NorthernMarianaIslands2
        extends Country("nm", "Northern Mariana Islands", discontinued = true)
    case NorthernTerritory                                        extends Country("xoa", "Northern Territory", discontinued = false)
    case NorthwestTerritories                                     extends Country("ntc", "Northwest Territories", discontinued = false)
    case Norway                                                   extends Country("no", "Norway", discontinued = false)
    case NovaScotia                                               extends Country("nsc", "Nova Scotia", discontinued = false)
    case Nunavut                                                  extends Country("nuc", "Nunavut", discontinued = false)
    case Ohio                                                     extends Country("ohu", "Ohio", discontinued = false)
    case Oklahoma                                                 extends Country("oku", "Oklahoma", discontinued = false)
    case Oman                                                     extends Country("mk", "Oman", discontinued = false)
    case Ontario                                                  extends Country("onc", "Ontario", discontinued = false)
    case Oregon                                                   extends Country("oru", "Oregon", discontinued = false)
    case Pakistan                                                 extends Country("pk", "Pakistan", discontinued = false)
    case Palau                                                    extends Country("pw", "Palau", discontinued = false)
    case Panama                                                   extends Country("pn", "Panama", discontinued = false)
    case PapuaNewGuinea                                           extends Country("pp", "Papua New Guinea", discontinued = false)
    case ParacelIslands                                           extends Country("pf", "Paracel Islands", discontinued = false)
    case Paraguay                                                 extends Country("py", "Paraguay", discontinued = false)
    case Pennsylvania                                             extends Country("pau", "Pennsylvania", discontinued = false)
    @deprecated("This code is no longer in use") case PeopleDemocraticRepublicYemen
        extends Country("ys", "Yemen (People's Democratic Republic)", discontinued = true)
    case Peru                                                     extends Country("pe", "Peru", discontinued = false)
    case Philippines                                              extends Country("ph", "Philippines", discontinued = false)
    case PitcairnIsland                                           extends Country("pc", "Pitcairn Island", discontinued = false)
    case Poland                                                   extends Country("pl", "Poland", discontinued = false)
    case Portugal                                                 extends Country("po", "Portugal", discontinued = false)
    @deprecated("This code is no longer in use") case PortugueseTimor
        extends Country("pt", "Portuguese Timor", discontinued = true)
    case PrinceEdwardIsland                                       extends Country("pic", "Prince Edward Island", discontinued = false)
    case PuertoRico                                               extends Country("pr", "Puerto Rico", discontinued = false)
    case Qatar                                                    extends Country("qa", "Qatar", discontinued = false)
    case Quebec                                                   extends Country("quc", "Québec (Province)", discontinued = false)
    case Queensland                                               extends Country("qea", "Queensland", discontinued = false)
    case Reunion                                                  extends Country("re", "Réunion", discontinued = false)
    case RhodeIsland                                              extends Country("riu", "Rhode Island", discontinued = false)
    case Romania                                                  extends Country("rm", "Romania", discontinued = false)
    case RussiaFederation                                         extends Country("ru", "Russia (Federation)", discontinued = false)
    @deprecated("This code is no longer in use") case RussianSFSR
        extends Country("rur", "Russian S.F.S.R.", discontinued = true)
    case Rwanda                                                   extends Country("rw", "Rwanda", discontinued = false)
    case SaintBarthelemy                                          extends Country("sc", "Saint-Barthélemy", discontinued = false)
    case SaintHelena                                              extends Country("xj", "Saint Helena", discontinued = false)
    case SaintKittsNevis                                          extends Country("xd", "Saint Kitts-Nevis", discontinued = false)
    @deprecated("This code is no longer in use") case SaintKittsNevisAnguilla
        extends Country("xi", "Saint Kitts-Nevis-Anguilla", discontinued = true)
    case SaintLucia                                               extends Country("xk", "Saint Lucia", discontinued = false)
    case SaintMartin                                              extends Country("st", "Saint-Martin", discontinued = false)
    case SaintPierreAndMiquelon                                   extends Country("xl", "Saint Pierre and Miquelon", discontinued = false)
    case SaintVincentAndTheGrenadines                             extends Country("xm", "Saint Vincent and the Grenadines", discontinued = false)
    case Samoa                                                    extends Country("ws", "Samoa", discontinued = false)
    case SanMarino                                                extends Country("sm", "San Marino", discontinued = false)
    case SaoTomeAndPrincipe                                       extends Country("sf", "Sao Tome and Principe", discontinued = false)
    case Saskatchewan                                             extends Country("snc", "Saskatchewan", discontinued = false)
    case SaudiArabia                                              extends Country("su", "Saudi Arabia", discontinued = false)
    case Scotland                                                 extends Country("stk", "Scotland", discontinued = false)
    case Senegal                                                  extends Country("sg", "Senegal", discontinued = false)
    case Serbia                                                   extends Country("rb", "Serbia", discontinued = false)
    @deprecated("This code is no longer in use") case SerbiaAndMontenegro
        extends Country("yu", "Serbia and Montenegro", discontinued = true)
    case Seychelles                                               extends Country("se", "Seychelles", discontinued = false)
    case SierraLeone                                              extends Country("sl", "Sierra Leone", discontinued = false)
    @deprecated("This code is no longer in use") case Sikkim      extends Country("sk", "Sikkim", discontinued = true)
    case Singapore                                                extends Country("si", "Singapore", discontinued = false)
    case SintMaarten                                              extends Country("sn", "Sint Maarten", discontinued = false)
    case Slovakia                                                 extends Country("xo", "Slovakia", discontinued = false)
    case Slovenia                                                 extends Country("xv", "Slovenia", discontinued = false)
    case SolomonIslands                                           extends Country("bp", "Solomon Islands", discontinued = false)
    case Somalia                                                  extends Country("so", "Somalia", discontinued = false)
    case SouthAfrica                                              extends Country("sa", "South Africa", discontinued = false)
    case SouthAustralia                                           extends Country("xra", "South Australia", discontinued = false)
    case SouthCarolina                                            extends Country("scu", "South Carolina", discontinued = false)
    case SouthDakota                                              extends Country("sdu", "South Dakota", discontinued = false)
    case SouthGeorgiaAndTheSouthSandwichIslands
        extends Country("xs", "South Georgia and the South Sandwich Islands", discontinued = false)
    case SouthKorea                                               extends Country("ko", "Korea (South)", discontinued = false)
    case SouthSudan                                               extends Country("sd", "South Sudan", discontinued = false)
    @deprecated("This code is no longer in use") case SouthVietnam
        extends Country("vs", "Vietnam, South", discontinued = true)
    @deprecated("This code is no longer in use") case SouthernRyukyuIslands
        extends Country("ry", "Ryukyu Islands, Southern", discontinued = true)
    @deprecated("This code is no longer in use") case SovietUnion
        extends Country("ur", "Soviet Union", discontinued = true)
    @deprecated("This code is no longer in use") case SovietUnion2
        extends Country("xxr", "Soviet Union", discontinued = true)
    case Spain                                                    extends Country("sp", "Spain", discontinued = false)
    case SpanishNorthAfrica                                       extends Country("sh", "Spanish North Africa", discontinued = false)
    case SpratlyIsland                                            extends Country("xp", "Spratly Island", discontinued = false)
    case SriLanka                                                 extends Country("ce", "Sri Lanka", discontinued = false)
    case Sudan                                                    extends Country("sj", "Sudan", discontinued = false)
    case Surinam                                                  extends Country("sr", "Surinam", discontinued = false)
    @deprecated("This code is no longer in use") case Svalbard    extends Country("sb", "Svalbard", discontinued = true)
    @deprecated("This code is no longer in use") case SwanIslands
        extends Country("sv", "Swan Islands", discontinued = true)
    case Sweden                                                   extends Country("sw", "Sweden", discontinued = false)
    case Switzerland                                              extends Country("sz", "Switzerland", discontinued = false)
    case Syria                                                    extends Country("sy", "Syria", discontinued = false)
    @deprecated("This code is no longer in use") case TajikSSR
        extends Country("tar", "Tajik S.S.R.", discontinued = true)
    case Tajikistan                                               extends Country("ta", "Tajikistan", discontinued = false)
    case Tanzania                                                 extends Country("tz", "Tanzania", discontinued = false)
    case Tasmania                                                 extends Country("tma", "Tasmania", discontinued = false)
    case Tennessee                                                extends Country("tnu", "Tennessee", discontinued = false)
    case TerresAustralesEtAntarctiquesFrancaises
        extends Country("fs", "Terres australes et antarctiques françaises", discontinued = false)
    case Texas                                                    extends Country("txu", "Texas", discontinued = false)
    case Thailand                                                 extends Country("th", "Thailand", discontinued = false)
    case TimorLeste                                               extends Country("em", "Timor-Leste", discontinued = false)
    case Togo                                                     extends Country("tg", "Togo", discontinued = false)
    case Tokelau                                                  extends Country("tl", "Tokelau", discontinued = false)
    case Tonga                                                    extends Country("to", "Tonga", discontinued = false)
    case TrinidadAndTobago                                        extends Country("tr", "Trinidad and Tobago", discontinued = false)
    @deprecated("This code is no longer in use") case TrustTerritoryOfThePacificIslands
        extends Country("tt", "Trust Territory of the Pacific Islands", discontinued = true)
    case Tunisia                                                  extends Country("ti", "Tunisia", discontinued = false)
    case Turkey                                                   extends Country("tu", "Turkey", discontinued = false)
    @deprecated("This code is no longer in use") case TurkmenSSR
        extends Country("tkr", "Turkmen S.S.R.", discontinued = true)
    case Turkmenistan                                             extends Country("tk", "Turkmenistan", discontinued = false)
    case TurksAndCaicosIslands                                    extends Country("tc", "Turks and Caicos Islands", discontinued = false)
    case Tuvalu                                                   extends Country("tv", "Tuvalu", discontinued = false)
    case Uganda                                                   extends Country("ug", "Uganda", discontinued = false)
    case Ukraine                                                  extends Country("un", "Ukraine", discontinued = false)
    @deprecated("This code is no longer in use") case UkraineOld  extends Country("unr", "Ukraine", discontinued = true)
    case UnitedArabEmirates                                       extends Country("ts", "United Arab Emirates", discontinued = false)
    case UnitedKingdom                                            extends Country("xxk", "United Kingdom", discontinued = false)
    @deprecated("This code is no longer in use") case UnitedKingdom2
        extends Country("uk", "United Kingdom", discontinued = true)
    @deprecated("This code is no longer in use") case UnitedKingdomMiscIslands
        extends Country("ui", "United Kingdom Misc. Islands", discontinued = true)
    @deprecated("This code is no longer in use") case UnitedKingdomMiscIslands2
        extends Country("uik", "United Kingdom Misc. Islands", discontinued = true)
    case UnitedStates                                             extends Country("xxu", "United States", discontinued = false)
    @deprecated("This code is no longer in use") case UnitedStates2
        extends Country("us", "United States", discontinued = true)
    case UnitedStatesMiscCaribbeanIslands
        extends Country("uc", "United States Misc. Caribbean Islands", discontinued = false)
    case UnitedStatesMiscPacificIslands
        extends Country("up", "United States Misc. Pacific Islands", discontinued = false)
    case Uruguay                                                  extends Country("uy", "Uruguay", discontinued = false)
    case Utah                                                     extends Country("utu", "Utah", discontinued = false)
    @deprecated("This code is no longer in use") case UzbekSSR
        extends Country("uzr", "Uzbek S.S.R.", discontinued = true)
    case Uzbekistan                                               extends Country("uz", "Uzbekistan", discontinued = false)
    case Vanuatu                                                  extends Country("nn", "Vanuatu", discontinued = false)
    case VariousPlaces                                            extends Country("vp", "Various places", discontinued = false)
    case VaticanCity                                              extends Country("vc", "Vatican City", discontinued = false)
    case Venezuela                                                extends Country("ve", "Venezuela", discontinued = false)
    case Vermont                                                  extends Country("vtu", "Vermont", discontinued = false)
    case Victoria                                                 extends Country("vra", "Victoria", discontinued = false)
    case Vietnam                                                  extends Country("vm", "Vietnam", discontinued = false)
    case VirginIslandsOfTheUnitedStates
        extends Country("vi", "Virgin Islands of the United States", discontinued = false)
    case Virginia                                                 extends Country("vau", "Virginia", discontinued = false)
    case WakeIsland                                               extends Country("wk", "Wake Island", discontinued = false)
    case Wales                                                    extends Country("wlk", "Wales", discontinued = false)
    case WallisAndFutuna                                          extends Country("wf", "Wallis and Futuna", discontinued = false)
    case WashingtonState                                          extends Country("wau", "Washington (State)", discontinued = false)
    case WestBankOfTheJordanRiver                                 extends Country("wj", "West Bank of the Jordan River", discontinued = false)
    @deprecated("This code is no longer in use") case WestBerlin
        extends Country("wb", "West Berlin", discontinued = true)
    case WestVirginia                                             extends Country("wvu", "West Virginia", discontinued = false)
    case WesternAustralia                                         extends Country("wea", "Western Australia", discontinued = false)
    case WesternSahara                                            extends Country("ss", "Western Sahara", discontinued = false)
    case Wisconsin                                                extends Country("wiu", "Wisconsin", discontinued = false)
    case Wyoming                                                  extends Country("wyu", "Wyoming", discontinued = false)
    case Yemen                                                    extends Country("ye", "Yemen", discontinued = false)
    case YukonTerritory                                           extends Country("ykc", "Yukon Territory", discontinued = false)
    case Zambia                                                   extends Country("za", "Zambia", discontinued = false)
    case Zimbabwe                                                 extends Country("rh", "Zimbabwe", discontinued = false)
end Country

object Country:
    def fromCode(code: String): Maybe[Country] =
        Country.values.find(_.code.toLowerCase == code.toLowerCase.trim).maybe
